name: My First GitHub Action

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Run Bash script
        run: bash DevOps_Docker_Labs/14_GitHub_Actions/hello.sh
